baseURL = "/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Abid's Thoughts"
theme = "anubis2"
paginate = 5

disqusShortname = ""

[author]
name = "Abid"
email = "abidkhan484@gmail.com"
location = "Bangladesh"

[params]
description = "Abid Khan's thought sharing platform"
dateFormat = "2024-06-20"
paginationSinglePost = true

colorTheme = "auto"
colorThemeSwitcher = true

readMore = false
readNextPosts = 2
copyCodeButton = true
rssAsSocialIcon = true
locale = "en-us"
math = false           # true: enable mathjax globally (default is false)
toc = true

# Graphcomment support
graphcommentId = ""

GiscusRepo = "abidkhan484/abidkhan484.github.io"
GiscusRepoId = "MDEwOlJlcG9zaXRvcnkyNTQ3MjI1NzI"
GiscusCategory = "General"
GiscusCategoryId = "DIC_kwDODy7CDM4CgOhG"
GiscusLazyLoad = true
GiscusDataMapping = "pathname"

social = [
  { id = "github", url = "https://github.com/abidkhan484" },
  { id = "linkedin", url = "https://www.linkedin.com/in/abidkhan484" },
  { id = "email", url = "mailto:abidkhan484@gmail.com" },
]

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 2

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 3

[[menu.main]]
name = "Archive"
identifier = "archive"
url = "/posts/"
weight = 4

[languages]
[languages.en]
languageName = "English"

[markup]
defaultMarkdownHandler = 'goldmark'

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
anchorLineNos = false
codeFences = true       # tested with true and false. Both work.
noClasses = true        # If you run with markup.highlight.noClasses=false in your site configuration, you need a style sheet.
style = 'base16-snazzy'
tabWidth = 4

[params.UmamiAnalytics]
enabled = true
dnt = false
id = "867dc0dc-2a13-49e2-8956-dca6fd97ebf0"                                                   # Website ID
datacache = false

[params.GoogleAnalytics]
enabled = true
gtag = "G-32F16X8HLF"
